interfGame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("", include("juego.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

juego/urls.py
from django.contrib import admin
from django.urls import include, path

# Views
from juego import views

app_name = "juego"
urlpatterns = [
path('space/', views.space, name = "space"),
path('tesoro/', views.tesoro, name = "tesoro"),
path('levels/', views.levels, name = "levels"),
path('rompecabezas/', views.rompecabezas, name = "rompecabezas"),
path('memorama/', views.memorama, name = "memorama"),
path('gato/', views.tictactoe, name = "gato"),
path('simon/', views.simon, name = "simon"),
path('encuentraCura/', views.encuentraCura, name = "encuentraCura"),
path('sopaDeLetras/', views.sopaLetras, name = "sopaDeLetras"),
path('gato/', views.tictactoe, name = "gato"),
path('simon/', views.simon, name = "simon"),
path('instruction/', views.inst, name = 'instruction'),
path('', views.home, name = 'index'),
path('mensaje1/', views.pres1, name = 'mensaje1'),
path('acept/', views.acept, name = 'acept'),
path('reject/', views.reject, name = 'reject'),
path('mesMemo/', views.histMemo, name = 'mesMemo'),
path('mesGato/', views.hisGato, name = 'mesGato'),
path('mesCasa/', views.hisCasa, name = 'mesCasa'),
path('casa/', views.casa, name = 'casa'),
path('boti/', views.boti, name = 'boti'),
path('hisBoti/', views.hisBoti, name = 'hisBoti'),
path('hisBusca/', views.hisBusca, name = 'hisBusca'),
path('simonhist/', views.simonhist, name = 'simonhist'),
path('hisNave/', views.hisNave, name = 'hisNave'),
path('win/', views.despedida, name = "win"),
path('hisSopa/', views.hisSopa, name = "hisSopa")
]

users/urls.py
from django.contrib import admin
from django.urls import include, path

# Views
from users import views

app_name = "users"
urlpatterns = [
    path('register/',views.registerPage, name="register"),
	path('login/',views.logPage, name="login"),
	path('home/', views.home, name="home"),
    path('direc/', views.direc, name = "direc"),
    path('logout/', views.logoutUser, name="logout"),
    path('homeadmin/', views.homeAdmin, name="homeAdmin"),
]

juego/models.py
from django.db import models

# Create your models here.

juego/views.py
# Create your views here.
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.decorators import login_required


@login_required(login_url='users:login')
def space(request):
    template = "juego/index.html"
    return render(request, template)
@login_required(login_url='users:login')
def tesoro(request):
	template = "juego/tesoro.html"
	return render(request, template)
@login_required(login_url='users:login')
def levels(request):
	template = "juego/levels.html"
	return render(request, template)

@login_required(login_url='users:login')
def rompecabezas(request):
	template = "juego/index2.html"
	return render(request, template)
@login_required(login_url='users:login')
def memorama(request):
	template = "juego/memorama.html"
	return render(request, template)

@login_required(login_url='users:login')
def tictactoe(request):
	template = "juego/gato.html"
	return render(request, template)

@login_required(login_url='users:login')
def simon(request):
	template = "juego/simondice.html"
	return render(request, template)
@login_required(login_url='users:login')
def encuentraCura(request):
	template = "juego/encuentraCura.html"
	return render(request, template)
@login_required(login_url='users:login')
def sopaLetras(request):
	template = "juego/sopaLetras.html"
	return render(request, template)
@login_required(login_url='users:login')
def inst(request):
	template = "juego/escrito.html"
	return render(request, template)

def home(request):
	template = "juego/home.html"
	return render(request, template)

def pres1(request):
	template = "juego/Mensaje1.html"
	return render(request, template)
def acept(request):
	template = "juego/aceptar.html"
	return render(request, template)

def reject(request):
	template = "juego/reject.html"
	return render(request, template)
def histMemo(request):
	template = "juego/HistoriaMemorama.html"
	return render (request, template)

def hisGato(request):
	template = "juego/insGato.html"
	return render (request, template)

def hisCasa(request):
	template = "juego/hisCasa.html"
	return render(request, template)

def casa(request):
	template = "juego/casa.html"
	return render (request, template)

def boti(request):
	template = "juego/botiquin.html"
	return render(request, template)

def hisBoti(request):
	template = "juego/hisBoti.html"
	return render(request, template)

def hisBusca(request):
	template = "juego/histBusca.html"
	return render (request, template)

def simonhist(request):
	template = "juego/historiaSimon.html"
	return render(request, template)

def hisNave(request): 
	template = "juego/hisNaves.html"
	return render(request, template)
def despedida(request):
	template = "juego/despedida.html"
	return render(request, template)

def hisSopa(request):
	template = "juego/hisWa.html"
	return render(request, template)

juego/templates/juego/HistoriaMemorama.html
     {% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <head>

		  <meta charset="UTF-8"/>
 		 <title>#QuédateEnCasa</title>
 		 <link rel="stylesheet" href="{%static '/css/game.css'%}" type="text/css" />
  			<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
  			<meta name="viewport" content="width=device-width, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"/>
 			<meta name="apple-mobile-web-app-capable" content="yes">
  			<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
			</head>
			<body>

			</body>

          <meta charset="UTF-8"/>
         <title>#QuédateEnCasa</title>
         <link rel="stylesheet" href="{%static '/css/game.css'%}" type="text/css" />
            <link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
            <meta name="viewport" content="width=device-width, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"/>
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
            </head>
            <body>

            </body>

        <!-- Favicon-->
      
        <link rel="icon" type="image/x-icon" href= "{%static '/img/assets/img/favicon.ico'%}">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static '/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top" onload="typeWriter()">
        <audio autoplay src="/static/img/Song_of_Sadhana.mp3" loop></audio>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">

                <a class="navbar-brand js-scroll-trigger" href="#page-top">Síntomas del Covid-19 ¡Identifícalos!</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        
                

                <a class="navbar-brand js-scroll-trigger" href="#page-top">Guerra Biológica</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">

                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        
        <!-- About-->
        <section class="page-section bg-dark text-white col-lg-12 ml-auto text-center mb-5 mb-lg-0">

          <a href="{% url 'juego:memorama' %}"><i class="fa fa-fw fa-play" style="font-size:80px;color:#63b525;"></i></a>
           <div class="container">

                <hr class="divider my-4 mt-5" />
                <div class="row">
                <p id="demo"></p>


			<script>
			var i = 0;
			var txt = 'Bien hecho @usuario encontraste el jabón. Ahora identifica los síntomas, emparejándolas con su respectiva imagen. Presiona el boton "Play" para empezar a jugar.';
			var speed = 40;

				function typeWriter() {
  				if (i < txt.length) {
    			document.getElementById("demo").innerHTML += txt.charAt(i);
   				 i++;
    			setTimeout(typeWriter, speed);
 				 }
			}
			</script>
			<div class="col-lg-12 ml-auto text-center mb-5 mb-lg-0"> 
                <img src="/static/img/sintomasmemo.png" align="center">
            </div>

            <script>
            var i = 0;
            var txt = 'Bien hecho encontraste el jabón. Ahora identifica los síntomas, emparejándolas con su respectiva imagen.';
            var speed = 40;

                function typeWriter() {
                if (i < txt.length) {
                document.getElementById("demo").innerHTML += txt.charAt(i);
                 i++;
                setTimeout(typeWriter, speed);
                 }
            }
            </script>
            

                     

                </div>

            </div>
        </section>
        
        <footer class="bg-light py-5">


            <div class="container"><div class="small text-center text-muted">Guerra Biológica - Facultad de Ciencias UNAM</div></div>

        </footer>
        <!-- Bootstrap  JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Scripts -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

juego/templates/juego/Mensaje1.html
  {% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <head>
		  <meta charset="UTF-8"/>
 		 <title>Instrucciones</title>
 		 <link rel="stylesheet" href="{%static '/css/game.css'%}" type="text/css" />
  			<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
  			<meta name="viewport" content="width=device-width, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"/>
 			<meta name="apple-mobile-web-app-capable" content="yes">
  			<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
			</head>
			<body>

			</body>
        <!-- Favicon-->
      
        <link rel="icon" type="image/x-icon" href= "{%static '/img/assets/img/favicon.ico'%}">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static '/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top" onload="typeWriter()">
        <audio autoplay src="/static/img/Song_of_Sadhana.mp3" loop></audio>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">México te necesita</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        
                       
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        
        <!-- About-->
        <section class="page-section bg-dark text-white col-lg-12 ml-auto text-center mb-5 mb-lg-0">

          
           <div class="container">

                <hr class="divider my-4 mt-5" />
                <div class="row">
                <p id="demo"></p>

			<script>
			var i = 0;
			var txt = '17 DE MARZO AÑO 2020, México entra en estado de cuarentena y se aproxima una nueva aventura para ti joven entusiasta.'+ 
            ' ¿Aceptarías ayudarnos a mejorar la situación actual?';
			var speed = 40;

				function typeWriter() {
  				if (i < txt.length) {
    			document.getElementById("demo").innerHTML += txt.charAt(i);
   				 i++;
    			setTimeout(typeWriter, speed);
 				 }
			}
			</script>
			
                    <div class="col-lg-12 ml-auto text-center mb-5 mb-lg-0">

         <a href="{% url 'juego:acept' %}"><i class="fa fa-fw fa-check" style="font-size:30px;color:#63b525;" src="/static/img/play.png"></i></a>
          <a href="{% url 'juego:reject' %}"><i class="fa fa-fw fa-window-close" style="font-size:30px;color:#d90007;"></i> </a>
        </div> 

                </div>

            </div>
        </section>
        
       <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Guerra Biológica - Facultad de Ciencias UNAM</div></div>
        </footer>
        <!-- Bootstrap core JS-->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

juego/templates/juego/encuentraCura.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Encuentra la cura</title>
  <link rel="stylesheet" href="{%static '/css/encuentra_style.css'%}">

</head>
<body>
  <audio autoplay src="/static/img/Dream_Lagoon.mp3" loop></audio>
<!-- partial:index.partial.html -->
<section class="menu">
  <h1>Encuentra la Cura</h1>
  <select class="difficult-select" name="select">
    <option value="easy">Easy</option> 
    <option value="medium" selected>Medium</option>
    <option value="hard">Hard</option>
  </select>
  <p class="score-box"></p>
  <button id="startBtn">Start</button>
</section>

<section class="board">
  <div class="time-box"></div>
  <div class="scope"></div>
</section>
<!-- partial -->
  <script  src="{% static '/js/scriptEC.js' %}"></script>

</body>
</html>

juego/templates/juego/gato.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Gato</title>
    <link rel="stylesheet" href="{%static './css/gatocss.css'%}" type="text/css"/>

</head>

<body>

    <audio autoplay src="/static/img/Gravity_Variations.mp3" loop></audio>
    <div class="container">
        <h1>Gato</h1>
        <div class="play-area">

        </div>
        <h2 id="winner"></h2>
        <button onclick="reset_board()">INICIAR / REINICIAR</button>
    </div>
    <script src="{% static './js/gatogame.js' %}"></script>

</body>

</html>

juego/templates/juego/levels.html
<!-- Top Songs -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Guerra Biológica</title>
        <!-- Favicon-->
        {% load static %}
        <link rel="icon" type="image/x-icon" href= "{%static '/img/assets/img/favicon.ico'%}">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static '/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <audio autoplay src="/static/img/Song_of_Sadhana.mp3" loop></audio>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'juego:index' %}">Guerra Biológica</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                      <!--   <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:home' %}">Menu</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:home' %}">Carrito</a></li> -->
                       
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Cerrar Sesión</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <section class="page-section bg-dark text-white">
           <div class="container">

                <h2 class="text-center mt-0">Elige un nivel</h2>
                <!-- Aqui empieza esta cosa -->
                <section id="portfolio">
                <div class="container-fluid p-0">
                    <div class="row no-gutters">
                        <div class="col-lg-4 col-sm-6">
                            <a class="portfolio-box" href="{% url 'juego:mensaje1' %}">
                                <!--Este redirecciona-->
                                <img class="img-fluid" src="/static/img/intro.png"  />
                                <div class="portfolio-box-caption">
                                    <div class="project-category text-white-50">Introducción</div>
                                    <div class="project-name">¿Podrás derrotar al virus?</div>  <!-- INTRODUCCION -->
                                </div></a>
                        </div>
                    <div class="col-lg-4 col-sm-7">
                        <a class="portfolio-box" href="{% url 'juego:instruction' %}">
                            <img class="img-fluid" src="/static/img/jabo.png"  />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 1</div>
                                <div class="project-name">Usa tu ingenio</div>  <!-- NIVEL1 -->
                            </div></a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:mesMemo' %}"
                            ><img class="img-fluid" src="/static/img/lupa.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 2</div>
                                <div class="project-name">Aventúrate ahora</div>  <!-- nivel2 --> 
                            </div></a>
                    </div>

                      <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:mesGato' %}"
                            ><img class="img-fluid" src="/static/img/pelea.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 3</div>
                                <div class="project-name">Gánale al virus</div>  <!-- NIVEL3 --> 
                            </div></a>
                    </div>

                      <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:mesCasa' %}"
                            ><img class="img-fluid" src="/static/img/busca.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 4</div>
                                <div class="project-name">Usa lo que ya aprendiste</div>  <!-- NIVEL4 --> 
                            </div></a>
                    </div>

                      <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:simonhist' %}"
                            ><img class="img-fluid" src="/static/img/dice.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 5</div>
                                <div class="project-name">¿Tienes buena memoria?</div>  <!-- NIVEL5 --> 
                            </div></a>
                    </div>



                          <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:hisBoti' %}"
                            ><img class="img-fluid" src="/static/img/look.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 6</div>
                                <div class="project-name">Abre bien los ojos</div>  <!-- NIVEL3 --> 
                            </div></a>
                    </div>

                      <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:hisSopa' %}"
                            ><img class="img-fluid" src="/static/img/letras.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 7</div>
                                <div class="project-name">¿Sabes acerca del COVID-19?</div>  <!-- NIVEL4 --> 
                            </div></a>
                    </div>

                      <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'juego:hisBusca' %}"
                            ><img class="img-fluid" src="/static/img/busca2.png" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">NIVEL 8</div>
                                <div class="project-name">Ayúdanos a encontrar la cura</div>  <!-- NIVEL5 --> 
                            </div></a>
                    </div>
                   

                    </div>
                </div>
            </div>
        </section>
                <!-- Aqui acaba esta cosa -->
                
                <hr class="divider my-4" />
                <div class="row">
                
                    
                    
                    </div>
                </div>

            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Guerra Biológica</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

juego/templates/juego/simondice.html
{% load static %}
<!DOCTYPE html>
<html >
	<head>
		<meta charset="UTF-8">
		<title>Simon Dice</title>
		
		<style type="text/css">
		body
		{
			text-align: center;
			background: #34495e;
			color: white; 
		}
		</style>
	
	
	</head>
<body>
	
	<h1>Simon Dice</h1> 
	<audio autoplay src="/static/img/Brain_Trust.mp3.mp3" loop></audio>
	<canvas width = "250" height = "250" id="rojo"></canvas>
	<canvas width = "250" height = "250" id="azul"></canvas> <br/>
	<canvas width = "250" height = "250" id="amarillo"></canvas>
	<canvas width = "250" height = "250" id="verde"></canvas>
	<p> Primero ve la secuencia y luego repítela apretando sobre los colores</p>
	<p><input type="button" id="boton" value="Iniciar"/></p>
	<script type="text/javascript"></script>
	
	</script>
	<script src="{% static './js/simon.js' %}"></script>
</body>
</html>