interfGame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("", include("juego.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

juego/urls.py
from django.contrib import admin
from django.urls import include, path

# Views
from juego import views

app_name = "juego"
urlpatterns = [
path('space/', views.space, name = "space"),
path('tesoro/', views.tesoro, name = "tesoro"),
path('levels/', views.levels, name = "levels"),
path('rompecabezas/', views.rompecabezas, name = "rompecabezas"),
path('memorama/', views.memorama, name = "memorama"),
path('gato/', views.tictactoe, name = "gato"),
path('simon/', views.simon, name = "simon"),
path('encuentraCura/', views.encuentraCura, name = "encuentraCura"),
path('sopaDeLetras/', views.sopaLetras, name = "sopaDeLetras"),
path('gato/', views.tictactoe, name = "gato"),
path('simon/', views.simon, name = "simon"),
path('instruction/', views.inst, name = 'instruction'),
path('', views.home, name = 'index'),
path('mensaje1/', views.pres1, name = 'mensaje1'),
path('acept/', views.acept, name = 'acept'),
path('reject/', views.reject, name = 'reject'),
path('mesMemo/', views.histMemo, name = 'mesMemo'),
path('mesGato/', views.hisGato, name = 'mesGato'),
path('mesCasa/', views.hisCasa, name = 'mesCasa'),
path('casa/', views.casa, name = 'casa'),
path('boti/', views.boti, name = 'boti'),
path('hisBoti/', views.hisBoti, name = 'hisBoti'),
path('hisBusca/', views.hisBusca, name = 'hisBusca'),
path('simonhist/', views.simonhist, name = 'simonhist'),
path('hisNave/', views.hisNave, name = 'hisNave'),
path('win/', views.despedida, name = "win"),
path('hisSopa/', views.hisSopa, name = "hisSopa")
]

users/urls.py
from django.contrib import admin
from django.urls import include, path

# Views
from users import views

app_name = "users"
urlpatterns = [
    path('register/',views.registerPage, name="register"),
	path('login/',views.logPage, name="login"),
	path('home/', views.home, name="home"),
    path('direc/', views.direc, name = "direc"),
    path('logout/', views.logoutUser, name="logout"),
    path('homeadmin/', views.homeAdmin, name="homeAdmin"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Customer(models.Model):
	users = models.ForeignKey(User,  on_delete=models.CASCADE, null=True)
	telefono = models.CharField(max_length=200, null=True)
	calle = models.CharField(max_length = 200 , null = False)
	interior = models.CharField(max_length = 100, null= True)
	exterior = models.CharField(max_length = 100, null = True)
	colonia = models.CharField(max_length = 100, null = True)
	codigoPostal = models.CharField(max_length = 100, null = True)
	entreCalle = models.CharField(max_length = 100, null = True)
	ycalle = models.CharField(max_length = 100, null = True)
	referencias = models.CharField(max_length = 200, null = True)
	

class UserProfile(models.Model):
	users = models.ForeignKey(User,  on_delete=models.CASCADE, unique=True)
	foto = models.ImageField(upload_to = "users/media/users/{instance.id}_{instance.name}_{filename}",null=True,blank = True)

	def __str__(self):
		return self.calle

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth import authenticate
from .models import*



class SignUpForm(forms.Form):
    """Sign up new user form."""

    first_name = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput())
    calle = forms.CharField(max_length=100)
    numero = forms.CharField(max_length=100)
    colonia = forms.CharField(max_length = 100)
    telefono = forms.CharField(max_length=100)
    codigoPostal = forms.CharField(max_length = 100)



class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).count()>0:
            raise forms.ValidationError("Este correo ya está registrado")
        return data

    def clean_user(self):
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).count()>0:
            raise forms.ValidationError("El nombre de usuario ya existe, intente con otro")
        return data


class CreateDirecForm(ModelForm):
    class Meta:
        model = Customer
        exclude = ["users"]

users/views.py
from django.shortcuts import render

 # Create your views here.
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from .decorators import*


# Create your views here.
from .models import *
from .forms import *


def registerPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				user = form.save()
				username = form.cleaned_data.get('username')
				group = Group.objects.get(name='customer')
				user.groups.add(group)
				messages.success(request, 'Cuenta creada con exito con el usuario: ' + username)

				return redirect('users:login')
			

		context = {'form':form}
		return render(request, 'users/register.html', context)
		
def direc(request):
		dire = CreateDirecForm()
		if request.method == 'POST':
			dire = CreateDirecForm(request.POST,)
			if dire.is_valid():
				dire = dire.save(commit=False)
				dire.users = request.user
				dire.save()
				return redirect('users:home')
			

		context = {'form':dire}
		return render(request, 'users/regis2.html', context)


def logPage(request):
	if request.user.is_authenticated:
		return redirect('juego:levels')
	else:

		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username = username, password = password)

			if user is not None:

				login(request, user)
				group = None
				if request.user.groups.exists():
					group = request.user.groups.all()[0].name

				if group == 'customer':
					return redirect('juego:levels')

				if group == 'admin':
					return redirect('juego:levels')
				
			else:
				messages.info(request, 'Usuario o contraseña incorrectos')
		context = {}
		return render(request, 'users/login.html',context)


@login_required(login_url='users:login')
def home(request):
	return render(request, 'users/.html',{} )


@login_required(login_url='users:login')
@admin_only
def homeAdmin(request):
	return render(request, 'users/menu.html',{} )


def logoutUser(request):
	logout(request)
	return redirect('users:login')





	

users/templates/users/direccion.html
<h3>Customer</h3>
<hr>
{% block body_content %}
<form enctype="multipart/form-data" action="." method="POST">
    {% csrf_token %}

    {% for field in form %}
    <div class="addDireccion">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <input value="Agregar" type="submit">
</form>
{% endblock body_content %}

users/templates/users/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>A Pandemic Adventure</title>
        <!-- Favicon-->
        {% load static %}
        <link rel="icon" type="image/x-icon" href= "{%static '/img/assets/img/favicon.ico'%}">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static '/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'users:home' %}">A Pandemic Adventure</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                      <!--   <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:home' %}">Menu</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:home' %}">Carrito</a></li> -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:home' %}">Perfil</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Cerrar Sesión</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Bienvenido {{request.user}}</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        
                        <a class="btn btn-primary btn-xl" href="{% url 'users:home' %}">Jugar</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Guerra Biólogica</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
	<title>Iniciar Sesión</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #34495e !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #2c5d7a;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #63b525 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #63b525 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">Iniciar Sesión</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user "></i></span>
							</div>

							<input type="text" name="username" placeholder="Nombre de usuario..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Contraseña..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links p-3 mb-2 bg-dark text-white">
						¿Aún no tienes cuenta? <a href="{% url 'users:register' %}" class="ml-2 text-success">Regístrate</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

users/templates/users/main.html
<!DOCTYPE html>
<html>
<head>
	<title>CRM</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

</head>
<body>
	<div class="container-fluid">
	



	
    </div>
	<hr>
	<h5>Our footer</h5>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

users/templates/users/menu.html
<!-- Top Songs -->

{% load static %}

{% block title %}{% endblock title %}

{% block body_content %}
    <h1>Menú Administrador:</h1>
    <span class="hello-msg">Hello, {{request.user}}" </a></span></span>

  	 <span ><a  class="hello-msg" href="{% url 'users:homeAdmin' %}">Administrar nivel</a></span>
 	 <span ><a  class="hello-msg" href="{% url 'users:logout' %}">Cerrar Sesión</a></span>
    
{% endblock body_content %}

users/templates/users/regis2.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #34495e !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #2c5d7a;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #63b525 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #63b525 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Datos de domicilio</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form enctype="multipart/form-data" action="." method="POST">
   						 {% csrf_token %}

    					{% for field in form %}
    					<div class="addDireccion">
       					 {{ field.errors }}
        				{{ field.label_tag }}
        				{{ field }}
   					 </div>
 					   {% endfor %}
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'users:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Telefono..';
		form_fields[2].placeholder='Calle...';
		form_fields[3].placeholder='Número exterior...';
		form_fields[4].placeholder='Número interior...';
		form_fields[5].placeholder='Colonia...';
		form_fields[6].placeholder='Código postal...';
		form_fields[7].placeholder='Entre calle...';
		form_fields[8].placeholder='Y calle...';
		form_fields[9].placeholder='Referencaias...';
		form_fields[10].placeholder='Foto...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #34495e !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #2c5d7a;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #63b525 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #63b525 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Regístrate</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Continuar">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links p-3 mb-2 bg-dark text-white">
						¿Ya tienes cuenta? <a href="{% url 'users:login' %}" class="ml-2">Ingresa</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nombre..';
		form_fields[2].placeholder='Correo..';
		form_fields[3].placeholder='Contraseña...';
		form_fields[4].placeholder='Confirma tu contraseña...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>